Fix 'undefined reference to __builtin_unwind_init' linker error (ArmCC) (part of commit 9379c66 from Unity-Technologies/bdwgc)
Issue #173 (bdwgc).

* include/private/gcconfig.h (HAVE_BUILTIN_UNWIND_INIT): Do not define
if __ARMCC_VERSION.