Fix 'undefined reference to GC_incremental' linker error in pthread_start (fix of commit 73d30d2)
GC_incremental is declared as static in case of NO_DEBUGGING.

* pthread_start.c [GC_PTHREADS && !GC_WIN32_THREADS]
(GC_inner_start_routine): Call GC_end_stubborn_change instead of
GC_dirty; add comment.