Fix undefined reference to GC_fault_handler_lock if AO_USE_PTHREAD_DEFS (fix of commit b838dc72e)
* include/private/gc_priv.h [THREADS && !GC_DISABLE_INCREMENTAL
&& !HAVE_LOCKFREE_AO_OR && (NO_MANUAL_VDB && !MPROTECT_VDB
|| !AO_HAVE_test_and_set_acquire)] (GC_acquire_dirty_lock,
GC_release_dirty_lock): Define as no-op.
* include/private/gc_priv.h [THREADS && !GC_DISABLE_INCREMENTAL
&& !HAVE_LOCKFREE_AO_OR] (GC_fault_handler_lock): Do not declare if
NO_MANUAL_VDB and not MPROTECT_VDB.