Fix 'undefined reference to __data_start' linker error (Android/aarch64) (a cherry-pick of commit 30990efee from 'release-8_0')
As of NDK r18b, __data_start symbol is only provided by bfd linker.

* include/private/gcconfig.h [AARCH64 && LINUX && PLATFORM_ANDROID]
(__data_start): Do not declare extern variable.
* include/private/gcconfig.h [AARCH64 && LINUX && PLATFORM_ANDROID]
(SEARCH_FOR_DATA_START): Define (instead of DATASTART).