Fix 'undefined reference to GC_wait_for_reclaim' linker error (fix commit f4d690e)
Issue #179 (bdwgc).

* include/private/gc_pmark.h [HAVE_CONFIG_H]: Do not include config.h
if already included from gc_priv.h (to avoid PARALLEL_MARK macro
redefinition in config.h after it was undefined in gcconfig.h).